name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'php', 'java' ]  # Now includes Java

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # 🛠️ Required: Build for Java
      - name: Build with Maven
        if: matrix.language == 'java'
        run: mvn install -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
