name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]  # Include javascript for compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # Only build Java — JavaScript doesn't need a build step
      - name: Build with Maven
        if: matrix.language == 'java'
        run: mvn install -DskipTests

      - name: No build needed for JavaScript
        if: matrix.language == 'javascript'
        run: echo "Skipping JS build step (not actively scanned)"

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
